export default [
    {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "barH",
        dormPrice: "50",
        category: "shirt",
        status: "SOLD OUT",
        dormAddress: "None",
        id: "shirt1",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Bray Hall",
        dormPrice: "50",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt2",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Cary Hall",
        dormPrice: "50",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt3",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Crockett Hall",
        dormPrice: "40",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt4",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Davison Hall",
        dormPrice: "50",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt5",
        rating: "4",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    },
    {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "XO Logo Tee",
        dormPrice: "40",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt6",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    },
    {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Nugent Hall",
        dormPrice: "40",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt7",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    },
    {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Hall Hall",
        dormPrice: "38",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt8",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Nason Hall",
        dormPrice: "40",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt9",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    },
    {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Sharp Hall",
        dormPrice: "38",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt10",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Warren Hall",
        dormPrice: "38",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "shirt11",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    },
    {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Beman and Brinsmade",
        dormPrice: "60",
        category: "shirt",
        status: "Available",
        dormAddress: "None",
        id: "s12",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Blitman",
        dormPrice: "35",
        category: "hat",
        status: "Available",
        dormAddress: "Limited Edition",
        id: "hat1",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Bryckwyck",
        dormPrice: "35",
        category: "hat",
        status: "Available",
        dormAddress: "Limited Edition",
        id: "hat2",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Colonie Apartments",
        dormPrice: "30",
        category: "keychain",
        status: "Available",
        dormAddress: "Limited Edition",
        id: "keychain1",
        rating: "3",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "Colvin and Albright",
        dormPrice: "30",
        category: "keychain",
        status: "Available",
        dormAddress: "Limited Edition",
        id: "keychain2",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }, {
        imageOne: "https://www.asc-cybernetics.org/2010/wp-content/uploads/2010/07/blitman.jpg",
        imageTwo: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageThree: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        imageFour: "https://www.alpha6294.com/History/ThetaXionCampus/ThetaXiChapterHouse/ThetaXi-ChapterHouse-Frontside.jpg",
        dormName: "E-Complex",
        dormPrice: "145",
        category: "painting",
        status: "SOLD OUT",
        dormAddress: "Limited Edition",
        id: "painting1",
        rating: "5",
        numRooms: 1,
        numBeds: 2,
        sqft: 140,
        ratingAmt: 120
    }
];